name: 'Build ktec/ergodone'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["ktec/ergodone"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'
